R2 solver
JuliaSmoothOptimizers/JSOSolvers.jl pull request #124
Opened 2022-07-15 16:31 UTC by nathanemac

This is a PR for R2 algorithm

2022-07-15 16:42 UTC, dpo commented
Please remove all files that are not part of this repo from your PR.

2022-07-25 21:17 UTC, dpo commented
@nathanemac

2022-07-25 21:27 UTC, dpo requested changes

2022-07-25 21:27 UTC, dpo commented on src/R2.jl
> +    A first-order quadratic regularization method for unconstrained optimization
```suggestion

A first-order quadratic regularization method for unconstrained optimization
```

2022-07-25 21:27 UTC, dpo commented on src/R2.jl
> +- η1 = T(0.3), η2 = T(0.7): step acceptance parameters
The default values in the solver are different.

2022-07-25 21:27 UTC, dpo commented on src/R2.jl
> +  x = solver.x .= copy(x0)
```suggestion
  x = solver.x .= x0
```

2022-07-25 21:27 UTC, dpo commented on src/R2.jl
> +  norm_∇fk=norm(∇fk)
```suggestion
  norm_∇fk = norm(∇fk)
```

2022-07-25 21:27 UTC, dpo commented on src/R2.jl
> +  σk = 2^round(log2(norm_∇fk + 1)) # The closest exact-computed power of 2 from ∇fk
Why is this a good initial value?

2022-07-25 21:27 UTC, dpo commented on src/R2.jl
> +  ϵ = atol + rtol*norm_∇fk
```suggestion
  ϵ = atol + rtol * norm_∇fk
```

2022-07-25 21:27 UTC, dpo commented on src/R2.jl
> +    ck .= x .- (∇fk./σk)
```suggestion
    ck .= x .- ∇fk ./ σk
```

2022-07-25 21:27 UTC, dpo commented on src/R2.jl
> +    ΔTk= norm_∇fk^2/ σk
```suggestion
    ΔTk= norm_∇fk^2 / σk
```

2022-07-25 21:27 UTC, dpo commented on src/R2.jl
> +  while !(optimal | tired)
If the initial point is optimal, the code doesn't print anything (just the header).

2022-07-25 21:27 UTC, dpo commented on test/test_solvers.jl
> +        ("R2",R2)
```suggestion
        ("R2", R2)
```

2022-07-27 12:05 UTC, dpo requested changes
@nathanemac there are many polluting files in here.

2022-08-06 00:17 UTC, tmigot commented
Hey @nathanemac ! Actually, the tests failed.

In particular, in the `jldoctest` could you modify the examples so that no logs are printed?
Then, the logs to the other failed tests are available here: https://github.com/JuliaSmoothOptimizers/JSOSolvers.jl/runs/7697880907?check_suite_focus=true

2022-08-12 16:42 UTC, paraynaud commented
Hey guys, I was wondering if the algorithm is stochastic when it uses a `KnetNLPModel`?
If not you could add a line that would change the current mini-batch for the next `obj, grad` evaluations.
```julia
isa(nlp) == reset_minibatch_train!(nlp)
```
similar to PQNNLPModel in `trunk`:
```julia
if isa(nlp, QuasiNewtonModel)
  ∇fn .-= ∇f
  @. ∇fn = -∇fn  # = ∇f(xₖ₊₁) - ∇f(xₖ)
  push!(nlp, s, ∇fn)
  ∇fn .= ∇f
end
```

The drawback of this is that `KnetNLPModels` must be in `JSOSolvers.jl` dependencies.

2022-08-12 18:57 UTC, dpo commented
It should be enough to implement the callback feature like here: https://github.com/JuliaSmoothOptimizers/JSOSolvers.jl/pull/113/files#diff-36c852523b6a7513a10b8a6bae21f1037eaa27484efc9042f75bbda46d9f529bR34

The plan is for all solvers to have a callback. Then a user using R2 and KnetNLPModels can simply call `reset_minibatch_train!()` in the callback.

2022-08-13 22:52 UTC, dpo commented
@nathanemac It also looks like all the tests fail here.
@tmigot Could you please help him?

2022-08-15 20:41 UTC, nathanemac commented
@dpo ,  problem on tests solved with @tmigot

2022-08-15 20:48 UTC, tmigot commented
Great job @nathanemac ! I suggest we add the callback in a separate PR.

2022-08-15 20:51 UTC, dpo approved these changes

2022-08-15 20:51 UTC, dpo commented
Many thanks @nathanemac and @tmigot !!!

2022-08-15 21:56 UTC, merged