Up abstract type and `solve!`
JuliaSmoothOptimizers/JSOSolvers.jl pull request #144
Opened 2022-09-13 20:41 UTC by tmigot

Use new structure from SolverCore 0.3. A follow-up will be to create solver structure for the nls-variants #131

2022-09-13 21:43 UTC, dpo requested changes

2022-09-13 21:43 UTC, dpo commented on src/R2.jl
>    cx::V
move stats out of here?

2022-09-13 21:43 UTC, dpo commented on src/R2.jl
> +  stats::GenericExecutionStats{T, V};
stats vs solver.stats

2022-09-14 15:46 UTC, tmigot commented on src/R2.jl
>    cx::V
Good idea, done.

2022-09-14 16:13 UTC, dpo requested changes
Except for R2, the body of the solvers still don't update `stats.iter`, etc.

2022-09-14 16:15 UTC, tmigot commented
> Except for R2, the body of the solvers still don't update `stats.iter`, etc.

Shouldn't we add this when adding the callback for each solver?

2022-09-14 16:16 UTC, dpo commented
ah, ok.

2022-09-14 16:16 UTC, dpo approved these changes

2022-09-14 16:22 UTC, merged