Update readme
JuliaSmoothOptimizers/JSOSolvers.jl pull request #159
Opened 2022-09-21 23:17 UTC by tmigot

The tutorial [to be done] will explain the kwargs, callback ...

2022-09-22 03:21 UTC, dpo commented
Any idea what's going on with the nightly failure?

2022-09-22 03:27 UTC, dpo requested changes

2022-09-22 03:27 UTC, dpo commented on README.md
> +or bound-constrained optimization
```suggestion
and bound-constrained optimization
```

2022-09-22 03:27 UTC, dpo commented on README.md
> +This package contains the implementation of four algorithms that are classical for unconstrained/bound-constrained nonlinear optimization:
```suggestion
This package provides an implementation of four classic algorithms for unconstrained/bound-constrained nonlinear optimization:
```

2022-09-22 03:27 UTC, dpo commented on README.md
> +- `lbfgs`: An implementation of a limited memory BFGS line-search method for unconstrained minimization.
```suggestion
- `lbfgs`: an implementation of a limited-memory BFGS line-search method for unconstrained minimization;
```

2022-09-22 03:27 UTC, dpo commented on README.md
> +- `R2`: A first-order quadratic regularization method for unconstrained optimization.
```suggestion
- `R2`: a first-order quadratic regularization method for unconstrained optimization;
```

2022-09-22 03:27 UTC, dpo commented on README.md
> +- `tron`: A pure Julia implementation of TRON a trust-region solver for bound-constrained optimization described in
```suggestion
- `tron`: a pure Julia implementation of TRON, a trust-region solver for bound-constrained optimization described in
```

2022-09-22 03:27 UTC, dpo commented on README.md
> +    The package also contains a variant for nonlinear least-squares.
```suggestion
    as well as a variant for nonlinear least-squares;
```

2022-09-22 03:27 UTC, dpo commented on README.md
> +- `trunk`: A trust-region solver for unconstrained optimization using exact second derivatives. This implementation follows the description given in
```suggestion
- `trunk`: a trust-region solver for unconstrained optimization using exact second derivatives. Our implementation follows the description given in
```

2022-09-22 08:19 UTC, tmigot commented
> Any idea what's going on with the nightly failure?

This happens randomly but regularly with this package with all the versions. It looks like some numerical instability that we never really investigated

2022-09-25 14:36 UTC, dpo approved these changes

2022-09-25 14:36 UTC, dpo commented on README.md
> +If you want to ask a question not suited for a bug report, feel free to start a discussion [here](https://github.com/JuliaSmoothOptimizers/Organization/discussions). This forum is for general discuss
every README should mention this!

2022-09-25 17:16 UTC, merged