Update R2.jl
JuliaSmoothOptimizers/JSOSolvers.jl pull request #228
Opened 2023-06-20 21:10 UTC by farhadrclass

Added a sigma_k tot he solver so we can access it in the callback

2023-06-20 21:11 UTC, farhadrclass commented
@dpo and @tmigot would you be able to review this ?

2023-06-20 21:17 UTC, tmigot requested changes
Hi @farhadrclass !
This looks good to me, would you be able to add a unit test accessing this new value (and making sure it is >0) in a callback in this file https://github.com/Farhad-phd/JSOSolvers.jl/blob/R2_sigma/test/callback.jl ?

Are there other values that might be eligible?

2023-06-20 21:18 UTC, farhadrclass commented
sure, let me add that,
for the moment we think that is the only one we need

2023-06-20 23:18 UTC, dpo requested changes

2023-06-20 23:18 UTC, dpo commented on src/R2.jl
> +  σk::T
```suggestion
  σ::T
```

2023-06-21 17:32 UTC, farhadrclass commented
@tmigot I added the test, and it is ready for review

2023-06-21 19:09 UTC, tmigot approved these changes
I just made a couple of suggestions to simplify the tests, after that it is good for me. I let @dpo have a look if needed.

2023-06-21 19:09 UTC, tmigot commented on test/callback.jl
> +    push!(Y, x[2])
```suggestion
```

2023-06-21 19:09 UTC, tmigot commented on test/callback.jl
> +  Y = [nlp.meta.x0[2]]
```suggestion
```

2023-06-21 22:50 UTC, farhadrclass commented
Thank you, 
I have applied the changes, Also I noticed a small error on my end that I fixed, 

Once it is passed, what should I do to include the code in R2?

2023-06-22 07:01 UTC, merged