Added warning message
JuliaSmoothOptimizers/JSOSolvers.jl pull request #246
Opened 2023-11-22 17:28 UTC by Jay-sanjay

This PR is related to #244 

## PR CheckList

- [x]  Added warning message in `tron.jl` and `tronls.jl`

2023-11-24 16:38 UTC, Jay-sanjay commented
@tmigot  Sir would you please provide workflows approval to this PR.

2023-11-26 12:31 UTC, tmigot requested changes

2023-11-26 12:31 UTC, tmigot commented on src/tron.jl
> +  if(verbose > 0)
Ok, but we need to show this warning if `verbose > 0` AND the initial guess provided is not within bounds.

2023-12-12 05:27 UTC, Jay-sanjay commented
bump.

2023-12-17 12:15 UTC, tmigot requested changes
Thank you for the updated suggestion, we are getting there!
Could you also add a unit test for this using @test_warn? https://docs.julialang.org/en/v1/stdlib/Test/#Test.@test_warn
This will improve coverage. Thanks !!

2023-12-17 12:15 UTC, tmigot commented on src/tron.jl
> +  if (verbose > 0 && (ℓ > x && x > u))
```suggestion
  if (verbose > 0 && !(u > x > ℓ))
```
looks more compact.

2023-12-17 12:15 UTC, tmigot commented on src/tronls.jl
> +  if(verbose > 0)
```suggestion
  if (verbose > 0 && !(u > x > ℓ))
```

2023-12-18 13:23 UTC, tmigot approved these changes
@Jay-sanjay I took the liberty to complete your PR. Thanks for your help.

2023-12-18 13:24 UTC, merged

2023-12-18 17:41 UTC, Jay-sanjay commented
Thanks @tmigot  for it, got a bit busy with my semester exams so could not find proper time for the PR ;) 
That said thanks for the help :)