Fomo nonmonotone extension
JuliaSmoothOptimizers/JSOSolvers.jl pull request #267
Opened 2024-04-05 16:52 UTC by d-monnet

Add non-monotone strategy to `fomo` solver.
Modifies conditions on momentum contribution.

2024-04-10 11:04 UTC, tmigot requested changes
Thanks @d-monnet for the PR! I made a first batch of comments.
You should also add unit tests for this variant.

2024-04-10 11:04 UTC, tmigot commented on src/fomo.jl
> +    ρk = (max_obj_mem - fck) /(max_obj_mem - stats.objective + ΔTk)
```suggestion
    ρk = (max_obj_mem - fck) / (max_obj_mem - stats.objective + ΔTk) 
```

2024-04-10 11:04 UTC, tmigot commented on src/fomo.jl
> +      circshift!(obj_mem,1)
```suggestion
      circshift!(obj_mem, 1)
```

2024-04-10 11:04 UTC, tmigot commented on src/fomo.jl
> +find_beta(m, mdot∇f, norm_∇f, μk, fk, max_obj_mem, β, θ1, θ2)
```suggestion
    find_beta(m, mdot∇f, norm_∇f, μk, fk, max_obj_mem, β, θ1, θ2)
```

2024-04-10 11:04 UTC, tmigot commented on src/fomo.jl
> +with fm the greatest objective value over the last M successful iterations, and fk = f(xk).
Ok, now I understand, it is the largest value over the last M iterations, if so, not need for the `best` indeed.

2024-04-10 13:08 UTC, d-monnet commented on src/fomo.jl
> +with fm the greatest objective value over the last M successful iterations, and fk = f(xk).
Yes it is, though largest is a better choice of word that greatest.

2024-04-11 12:17 UTC, tmigot commented on src/fomo.jl
> +with fm the greatest objective value over the last M successful iterations, and fk = f(xk).
Agreed, `largest` would be better.

2024-04-11 12:22 UTC, tmigot reviewed
@d-monnet Would you have a simple example or an illustration of the nonmonotone vs. monotone?

2024-04-11 12:22 UTC, tmigot commented on src/fomo.jl
> +Compute βmax which saturates the contibution of the momentum term to the gradient.
```suggestion
Compute βmax which saturates the contribution of the momentum term to the gradient.
```

2024-04-11 16:31 UTC, d-monnet commented
> @d-monnet Would you have a simple example or an illustration of the nonmonotone vs. monotone?

Not a simple example, but here are the perf profile (iterations) for `R2`, `TR`, and `fomo` with r2 and tr steps.
Profiles were obtained on 74 unconstrained problems of ADNLPProblems, run with Float64 with `atol=rtol = 1e-4` and default parameters.

![FOMO(R2)_1000](https://github.com/JuliaSmoothOptimizers/JSOSolvers.jl/assets/70266099/08cce240-38e5-45e9-9c91-ab5415abf735)
![FOMO(TR)_1000](https://github.com/JuliaSmoothOptimizers/JSOSolvers.jl/assets/70266099/be07fed7-efb9-4e2e-ae51-a9b8649c217a)
![R2_1000](https://github.com/JuliaSmoothOptimizers/JSOSolvers.jl/assets/70266099/7bd508d2-4723-4c47-9107-6f2439e03eea)
![TR_1000](https://github.com/JuliaSmoothOptimizers/JSOSolvers.jl/assets/70266099/ecffaf9d-e9ba-466d-9338-61e4adbc15fc)

2024-04-12 11:44 UTC, tmigot approved these changes
Thanks @d-monnet it looks good to me! Just one last typo.

When updating your branch to the current code, in JSO, we use `git rebase` instead of `git merge`. This would avoid duplicating the changes in your PR.

2024-04-12 11:44 UTC, tmigot commented on src/fomo.jl
> +with `m` the momentum term and `mdot∇f = ∇f(xk)ᵀm`, `fk` the model at s=0, `max_obj_mem` the largest value of objective over the last M successful iterations.
```suggestion
with `m` the momentum term and `mdot∇f = ∇f(xk)ᵀm`, `fk` the model at s=0, `max_obj_mem` the largest objective value over the last M successful iterations.
```

2024-04-13 17:01 UTC, d-monnet commented
> Thanks @d-monnet it looks good to me! Just one last typo.
> 
> When updating your branch to the current code, in JSO, we use `git rebase` instead of `git merge`. This would avoid duplicating the changes in your PR.

That's what I was planning to do, but I messed something up with VS Code interface...

2024-04-13 17:02 UTC, d-monnet commented
> > > @d-monnet Would you have a simple example or an illustration of the nonmonotone vs. monotone?
> > 
> > 
> > Not a simple example, but here are the perf profile (iterations) for `R2`, `TR`, and `fomo` with r2 and tr steps. Profiles were obtained on 74 unconstrained problems of ADNLPProblems, run with Float64 with `atol=rtol = 1e-4` and default parameters.
> > Looks like we have a bug with the labels when using `label` kwargs with `profile_solvers` by the way: 2 by 2 comparison labels are wrong.
> > ![FOMO(R2)_1000](https://private-user-images.githubusercontent.com/70266099/321710337-08cce240-38e5-45e9-9c91-ab5415abf735.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5MjIxNjQsIm5iZiI6MTcxMjkyMTg2NCwicGF0aCI6Ii83MDI2NjA5OS8zMjE3MTAzMzctMDhjY2UyNDAtMzhlNS00NWU5LTljOTEtYWI1NDE1YWJmNzM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEyVDExMzc0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmNWE3YjBhNTlmYmM2OGRlNzFjNzhmMjBlMzUxY2IwZjE2NmIzZTdlMDQ1ZDdiZGQ0ZDdkMzk1MDExZDA0YzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IsKHolpJKYJkdG3NWDsIM5EYnjWfLucOW9BBlvXsv2Y) ![FOMO(TR)_1000](https://private-user-images.githubusercontent.com/70266099/321710341-be07fed7-efb9-4e2e-ae51-a9b8649c217a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5MjIxNjQsIm5iZiI6MTcxMjkyMTg2NCwicGF0aCI6Ii83MDI2NjA5OS8zMjE3MTAzNDEtYmUwN2ZlZDctZWZiOS00ZTJlLWFlNTEtYTliODY0OWMyMTdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEyVDExMzc0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiOTNkOTBmYjJhNzdjOTJhYzJiNzM0MzliZTkwOGEyMDUzZmZiOGFkMmE3MjQwN2FmMmQyZjI1ZTYzMWY3MDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bsEs1e3E9RlqjV_PoJbXPxT0GcRVdPK-guAHGlUoWPQ) ![R2_1000](https://private-user-images.githubusercontent.com/70266099/321710344-7bd508d2-4723-4c47-9107-6f2439e03eea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5MjIxNjQsIm5iZiI6MTcxMjkyMTg2NCwicGF0aCI6Ii83MDI2NjA5OS8zMjE3MTAzNDQtN2JkNTA4ZDItNDcyMy00YzQ3LTkxMDctNmYyNDM5ZTAzZWVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEyVDExMzc0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmOWM5YTNmOTJhNWJhZjU2NzUyNTg1ZTExM2I4YzdhNTFlM2M1YWYwYjYxMWVjZTkzNDAzNDljMGMzNmRjZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hGF2QrBTQRTc01vYIiPEH0SbQP9OaGOq66hOGdYNezE) ![TR_1000](https://private-user-images.githubusercontent.com/70266099/321710345-ecffaf9d-e9ba-466d-9338-61e4adbc15fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5MjIxNjQsIm5iZiI6MTcxMjkyMTg2NCwicGF0aCI6Ii83MDI2NjA5OS8zMjE3MTAzNDUtZWNmZmFmOWQtZTliYS00NjZkLTkzMzgtNjFlNGFkYmMxNWZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEyVDExMzc0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjNGQ4MGY5MGFkZGM2NjE0MTZiOTc3OWE5NzY3NjA0ZDgzN2RkMDFmZGI5OGJiODM5OTkzYjRhMzFhOWUzY2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.34dHuwrr3iLP1pI-u_VxZzN6j-daoygD_wbZWxt-FyU)
> 
> That's awesome! In case, you still have the result of this benchmark, maybe you can find an example of a problem that has been solved by nonmonotone that has not been solved by monotone? I think we should plan a relatively short tutorial on this 1D methods and such an example would be really great.

I'll look into it and start working on a tutorial.

2024-04-13 19:15 UTC, merged